---
name: Conform Code

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mistweaverco/kulala-nvim-testrunner:latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        name: Run linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .
